
source 'https://git.coding.net/AlexsGuo/FXSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
target 'FXShareCenter_Example' do
  pod 'FXShareCenter', :path => '../'

  target 'FXShareCenter_Tests' do
    inherit! :search_paths

    
  end
end
